Xaymar/obs-StreamFX

source/obs-audio-capture.hpp
to declare the `shared_ptr` name
=> obs-audio-capture.hpp: missing memory include

.github/workflows/main.yml, CMakeLists.txt
Adds support for local plugin packages, and adds multiple GCC versions to the CI build script.
OBS Studio on Linux support loading plugins from `~/.config/obs-studio/plugins` which is a much better way to load plugins. Additionally someone might be building with a different GCC version which may result in crashes when the pugin is used.
Worked fine on my Laptop once the correct GCC version was used.
- Bug fix (non-breaking change which fixes an issue)
=> Support local plugin installs and build for multiple GCC versions

data/locale/en-US.ini, source/encoders/codecs/prores.hpp, source/encoders/ffmpeg-encoder.cpp, source/encoders/handlers/prores_aw_handler.cpp
Due to an oversight while renaming some defines, some encoders that did not support YUV 4:2:0 stopped working. With this they start working again.
ProRes is currently broken as it tries to select YUV 4:2:0 always.
ProRes started working again.
- Bug fix (non-breaking change which fixes an issue)
- Code cleanup (non-breaking change which makes code smaller or more readable)
=> Fix Color Format detection and ProRes

CMakeLists.txt
Removes the lib prefix, which is apparently not meant for shared modules/libraries that are plugins to something, but instead meant for global shared libraries. Makes no sense to me why this is different, and may be reverted in the future when StreamFX does start exporting other symbols again.
Dunno, but it was requested in #135. Apparently breaks the FreeBSD ports framework.
Hasn't.
- Breaking change (fix or feature that would cause existing functionality to change)
=> cmake: Don't add lib prefix to binary files

source/filters/filter-blur.cpp, source/filters/filter-blur.hpp, source/filters/filter-color-grade.cpp, source/filters/filter-color-grade.hpp, source/filters/filter-displacement.cpp, source/filters/filter-displacement.hpp, source/filters/filter-dynamic-mask.cpp, source/filters/filter-dynamic-mask.hpp, source/filters/filter-nv-face-tracking.cpp, source/filters/filter-nv-face-tracking.hpp, source/filters/filter-sdf-effects.cpp, source/filters/filter-sdf-effects.hpp, source/filters/filter-shader.cpp, source/filters/filter-shader.hpp, source/filters/filter-transform.cpp, source/filters/filter-transform.hpp, source/obs/obs-source-factory.hpp, source/sources/source-mirror.cpp, source/sources/source-mirror.hpp
Previously sources had to manually implement migration code, which resulted in unresolvable regression issues due to the lack of version and commit tagging. With the new migration code, all sources automatically have this version and commit tagging at all times, and as such can now have a temporary regression fixed without the user needing to change any values manually.
Testing in progress.
- Code cleanup (non-breaking change which makes code smaller or more readable)
=> obs-source-factory: Add settings migration code

.github/workflows/main.yml, CMakeLists.txt
Allows the creation of UI elements via Qt and using the OBS Studio Frontend API, if they are available during the configuration process. The frontend is considered an optional part and the plugin can be built without the frontend if necessary.
I'd like to add an About dialog and other things to OBS Studio to thank all the people supporting me. Also to make it easier to find updates.
Was the verification for [this PR](https://github.com/obsproject/obs-studio/pull/2650) - ended up working.
- New feature (non-breaking change which adds functionality)
=> cmake: Add support for OBS Frontend API and Qt UI

source/filters/filter-nv-face-tracking.cpp, source/filters/filter-nv-face-tracking.hpp, source/nvidia/cuda/nvidia-cuda-context.cpp, source/nvidia/cuda/nvidia-cuda-gs-texture.cpp, source/nvidia/cuda/nvidia-cuda-stream.cpp, source/nvidia/cuda/nvidia-cuda-stream.hpp, source/nvidia/cuda/nvidia-cuda.cpp, source/nvidia/cuda/nvidia-cuda.hpp, source/obs/gs/gs-helper.hpp, source/obs/obs-tools.hpp, source/util-threadpool.cpp
Through the use of asynchronous threaded tracking, the filter can gain some performance and free up render time in libOBS. Additionally increasing the CUDA stream priority prevents other GPU users from overpowering our request to use resources.
- #150 Performance trouble with Nvidia Face Tracking
=> Nvidia Face Tracking: Convert to asynchronous threaded tracking

.clang-tidy, CMakeLists.txt
As shown earlier in #115, a static analyzer can show code problems that would otherwise be left undetected. `clang-tidy` is a perfect candidate for this as it comes bundled with the clang toolset, and is by far the most advanced static analyzer that is available for free. Additionally since it is cross-platform it enables it to be used everywhere.
This adds it to the CMake projects as StreamFX_CLANG-TIDY so that it can simple be "built" by cmake. The script first generated compile_commands.json for each build configuration, which are then used by clang-tidy later on.
=> cmake: Add support for running clang-tidy

source/common.hpp
Fixes some issues with standard C++ breaking due to OBS redefining reserved names as something else.
=> common: Undefine the unsafe 'strtoll' define from libobs

CMakeLists.txt, source/configuration.cpp, source/configuration.hpp, source/obs/obs-tools.hpp, source/plugin.cpp
Add a global configuration handler that stores per-user plugin configuration, which is not handled by OBS Studio. Things such as UI related settings should be stored in here instead of shoving it into other settings.
=> Add global configuration handler

CMakeLists.txt, source/plugin.cpp, source/windll.cpp
Moves Windows exclusive library functionality into it's own file, instead of polluting plugin.cpp.
=> cmake: Place Windows exclusive functionality into own file

.github/workflows/main.yml
Visual Studio 2017 is now 3 years out of date, and newer options are available - and also produce better and faster binaries.
=> project: Remove the usage of Visual Studio 2017

CMakeLists.txt
Fixes the issue with the lack of the linking to stdc++fs, which is required in order to get full C++17 on GNU GCC and Clang < 9.0.
=> cmake: Link to stdc++fs on GNU compatible and Clang

.github/workflows/main.yml, source/util-event.hpp, source/util-profiler.cpp
Adds Clang-9 to the supported compilers which is a more optimized compiler than GCC and cross-platform as well. Additionally adds caching of dependencies in order to reduce build times.
- #146 Clang issues
=> ci: Add Clang and ignore Crowdin branches

source/ui/ui.cpp
Q_INIT_RESOURCE and Q_CLEANUP_RESOURCE can't be called from within a namespace and instead have to be in outside of the namespace, so by moving them into small inline functions we can fulfill this restriction.
- #192 Missing Qt symbol on Arch Linux
- #155 Binaries not working on various distros
=> ui: Fix incorrect namespace for Qt symbol

data/effects/mipgen.effect, source/filters/filter-transform.cpp, source/filters/filter-transform.hpp, source/obs/gs/gs-mipmapper.cpp, source/obs/gs/gs-mipmapper.hpp, source/obs/gs/gs-vertexbuffer.cpp, source/strings.hpp
The new libOBS API allows us to directly access the underlying API instead of having to mess around in memory. By using it we can avoid crashing in case the compiler for it is different, or in case the actual back end structure changes.
Additionally the mostly unimplemented and unused options have also been removed, which streamlines the use of this class even further and reduces both shader and code complexity.
Finally by optimizing the use of the internal render target we can achieve a speed up of up to 3000% over the old way, allowing for many more mipmapped filters.
- #129 Linux/Mac have no mipmapping support
- #166 Weird artifacts when using mipmapping in 3D Transform on Browser sources.
=> gs-mipmapper: ~2000% performance improvement and removal of unimplemented functionality

CMakeLists.txt, source/filters/filter-blur.cpp, source/filters/filter-color-grade.cpp, source/filters/filter-displacement.cpp, source/filters/filter-dynamic-mask.cpp, source/filters/filter-nv-face-tracking.cpp, source/filters/filter-nv-face-tracking.hpp, source/filters/filter-sdf-effects.cpp, source/filters/filter-shader.cpp, source/filters/filter-transform.cpp, source/gfx/blur/gfx-blur-box-linear.cpp, source/gfx/blur/gfx-blur-box.cpp, source/gfx/blur/gfx-blur-dual-filtering.cpp, source/gfx/blur/gfx-blur-gaussian-linear.cpp, source/gfx/blur/gfx-blur-gaussian.cpp, source/gfx/gfx-source-texture.cpp, source/obs/gs/gs-helper.cpp, source/obs/gs/gs-helper.hpp, source/obs/gs/gs-mipmapper.cpp, source/sources/source-mirror.cpp, source/sources/source-shader.cpp, source/transitions/transition-shader.cpp
Adds a new CMake option "ENABLE_PROFILING" which enables all CPU and GPU performance profiling available in StreamFX for tracking what's actually causing things to be slow. This option defaults to off, so release builds are not impacted by this.
- #199 Look into additional optimizations.
- #150 Downscaling for Nvidia Face Tracking
=> project: Improve performance profiling support

source/obs/gs/gs-helper.cpp, source/obs/gs/gs-helper.hpp
Allows compilers to inline functions without requiring link time code generation to be enabled, slightly improving performance for these functions.
=> Allow inlining various functions

data/locale/en-US.ini, source/filters/filter-nv-face-tracking.cpp, source/filters/filter-nv-face-tracking.hpp, source/nvidia/cuda/nvidia-cuda-context.cpp, source/nvidia/cuda/nvidia-cuda-context.hpp, source/nvidia/cuda/nvidia-cuda.cpp, source/nvidia/cuda/nvidia-cuda.hpp
Moves geometry and filtering into the video tick call, which happens much more frequently than the tracking updates, allowing for smoother continuous tracking. As filtering is no longer happening in the tracking thread, an additional velocity variable was added in order to smooth over time periods where tracking is not in sync with rendering, or otherwise delayed. 
Furthermore all the tracking values are now in 0..1 space, or UVs, which simplifies the logic necessary to render things, while slightly increasing the cost of the math in the tracking thread. This was combined with the fix to #206, which should now work properly again.
Also removes the high priority CUDA stream as it just causes collisions with NVENC and OBS rendering, which is not what we want. 
- Fixes #206 Filter changes …
=> NVIDIA Face Tracking Filter: Reduce impact on games, asynchronous tracking, and more

source/ui/ui-common.hpp, source/ui/ui.cpp
Moves the menu for StreamFX to the primary menu, so that it is not hidden under tools. This makes it clearer to the user if their installation of StreamFX is working correctly, in addition to reducing the steps necessary to use the menu.
Also the 'About StreamFX' dialog now actually shows up for every update, as expected.
=> ui: Fix about dialog not being shown and move menu

source/configuration.cpp, source/configuration.hpp
Fixes saving the configuration when a configuration file already exists.
=> configuration: Fix failed saving due to invalid path

source/common.hpp, source/filters/filter-blur.cpp, source/filters/filter-color-grade.cpp, source/filters/filter-displacement.cpp, source/filters/filter-dynamic-mask.cpp, source/filters/filter-nv-face-tracking.cpp, source/filters/filter-sdf-effects.cpp, source/filters/filter-shader.cpp, source/filters/filter-transform.cpp, source/obs/obs-source-factory.hpp, source/sources/source-mirror.cpp, source/sources/source-shader.cpp, source/strings.hpp, source/transitions/transition-shader.cpp
Enables the use of proxy registrations to maintain compatibility with older versions.
While newer versions of the plugin would stay compatible, older versions might use an incorrect or outdated id to identify themselves - therefore changing the id would break configurations. With this fix we can register both and have the old id as a hidden handler for the old registrations.
=> Allow regristration of Proxy sources/filters/transitions

source/filters/filter-nv-face-tracking.cpp, source/nvidia/cuda/nvidia-cuda-context-stack.cpp, source/nvidia/cuda/nvidia-cuda-context.cpp, source/nvidia/cuda/nvidia-cuda-context.hpp, source/nvidia/cuda/nvidia-cuda-gs-texture.cpp, source/nvidia/cuda/nvidia-cuda-gs-texture.hpp, source/nvidia/cuda/nvidia-cuda-memory.cpp, source/nvidia/cuda/nvidia-cuda-memory.hpp, source/nvidia/cuda/nvidia-cuda-stream.cpp, source/nvidia/cuda/nvidia-cuda-stream.hpp, source/nvidia/cuda/nvidia-cuda.cpp, source/nvidia/cuda/nvidia-cuda.hpp
Converts the CUDA class into a Singleton in order to avoid loading the library multiple times, which might cause weird effects.
=> Convert CUDA class into a singleton

source/obs/obs-encoder-factory.hpp
Fixes a typo in the code that caused the proxy registration to modify the original object, flooding the encoder list with entries.
=> obs/encoder-factory: Fix incorrect proxy registration

source/configuration.cpp, source/ui/ui.cpp
Fixes a memory leak caused by the configuration and adds exception messages for debugging purposes. The leak is kind of weird, but may be completely explainable by the standard. 
In ui/ui.cpp a copy of the shared_ptr is created, which is then used to get a copy of the internal shared_ptr, which is then used to get the actual obs_data_t. This series of steps somehow increases the reference count to both shared_ptrs permanently, and does not decrement it again. Since they are now always above 0 references, they end up leaking past the module lifetime.
=> Fix memory leak caused by configuration object and UI

source/obs/obs-source-tracker.cpp, source/obs/obs-source-tracker.hpp
Fixes a memory leak caused by not releasing the weak pointer generated when creating sources.
=> Fix memory leak caused by obs::source_tracker

source/plugin.cpp
Fixes a compiling error that happens when no features are selected, due to the namespace actually not existing.
=> Don't use 'using namespace' for namespaces that may not exist

source/common.hpp, source/configuration.cpp, source/encoders/encoder-ffmpeg.cpp, source/encoders/handlers/debug_handler.cpp, source/encoders/handlers/nvenc_h264_handler.cpp, source/encoders/handlers/nvenc_hevc_handler.cpp, source/encoders/handlers/nvenc_shared.cpp, source/encoders/handlers/prores_aw_handler.cpp, source/ffmpeg/tools.cpp, source/filters/filter-blur.cpp, source/filters/filter-color-grade.cpp, source/filters/filter-dynamic-mask.cpp, source/filters/filter-nv-face-tracking.cpp, source/filters/filter-sdf-effects.cpp, source/filters/filter-transform.cpp, source/gfx/blur/gfx-blur-box-linear.cpp, source/gfx/blur/gfx-blur-box.cpp, source/gfx/blur/gfx-blur-dual-filtering.cpp, source/gfx/shader/gfx-shader.cpp, source/obs/obs-encoder-factory.hpp, source/obs/obs-source-factory.hpp, source/obs/obs-source-tracker.cpp, source/obs/obs-source.cpp, source/obs/obs-tools.cpp, source/plugin.cpp, source/ui/ui.cpp
Prevents potential macro confusion in other compilers by ensuring that the name of the log macro is unique.
=> Rename LOG_ to DLOG_ in order to prevent ambigious macro names

source/obs/gs/gs-helper.hpp, source/obs/gs/gs-vertexbuffer.cpp, source/obs/gs/gs-vertexbuffer.hpp, source/utility.cpp
Fixes a leak directly caused by gs::vertex_buffer, and works around a leak caused by OBS Studio. Unfortunately does not fully removed the leak, as 5 memory allocations are left over at the end of the runtime.
=> Fix a leak caused by gs::vertex_buffer, and work around a leak in OBS Studio

.github/workflows/main.yml
Replaces the build script for 19.10 with the one for 20.04, which is now the stable version of Ubuntu.
=> ci: Replace Ubuntu 19.10 with Ubuntu 20.04

source/util/util-threadpool.cpp
Fixes a bug that would cause the worker thread to hold a reference to a task until another task replaces it due to an oversight in where the std::shared_ptr was allocated. By explicitly clearingthe pointer, we can prevent this unwanted reference from existing after the work has finished.
=> util/threadpool: Don't hold work endlessly after processing it

source/ui/ui.cpp
Fixes a potential crash if sourceTex is null, and adds support for disambiguation translation. This allows us to create UI files with test text, while still supporting real translations.
=> ui: Fix support for disambiguation in translations

templates/installer.iss.in
Fixes the installer running in 32-bit mode, despite 64-bit being the only supported official architecture. Also fixes the program files path not being resolved properly when obs-studio is not installed.
=> templates: Fix installation path and 64-bit installations

source/ui/ui-updater.cpp, source/ui/ui-updater.hpp, ui/updater.ui
In order to work around a bug in the OBS Studio UI code, we have to swap our modal status right before showing and right after hiding, so that the OBS Studio tray menu continuous working correctly. This is a bit of a weird solution, but it does work as expected.
- #343 "Hide" option in tray menu not working.
- [obs-studio/#3518](https://github.com/obsproject/obs-studio/issues/3518) OBS Studio UI checks for invisible message boxes and modals.
=> ui/updater: Apply workaround for OBS Studio checking for modals

source/encoders/handlers/debug_handler.cpp
Not returning anything is illegal. Triggers a compiler error with
strict flags.
None
=> debug handler's to_string(): Return something by default

data/examples/shaders/filter/hexagonize.effect
Current Hexagonize effect creates hexagons with incorrect angles. This is due to an incorrect value for deg30.
Should be pi/6 radians, not pi/15 radians.
=> Corrected value for deg30

source/ui/ui-updater.cpp
Initializes all updater variables to 0 in order to fix a crash.
OBS Studio may crash on launch if StreamFX is installed.
OBS Studio no longer crashes on launch.
=> ui/updater: Always initialize members to zero

CMakeLists.txt
Updates the dependency for libOBS to 26.0.x, including the OBS dependencies.
Previously built against 25.0.x
Now builds against 26.0.x
=> cmake: Update to libOBS 26.0.x

source/ui/ui-updater.cpp
This fixes a bug with older Qt versions which would not remove the modal window from the parent in the setModal() call, resulting in an unusable parent window.
Clicking anything but the "X" of the dialog causes OBS to enter an unusable state due to an old Qt version being used.
Clicking any of the close options correctly hides the dialog, so that the modal is no longer blocking OBS from being used.
- #368 OBS Studio is blocked by an invisible modal
=> ui/updater: Set modal flag after hiding the dialog

CMakeLists.txt
The MODULE_EXPORT and EXPORT macros in libOBS do not correctly mark a function or type as visible on GCC, which results in the newly added flag hiding everything from view, instead of just what should be hidden.
Linux and Mac binaries did not load.
Linux and Mac binaries should now load again.
- #372 'obs_module_load' missing
=> cmake: Restore default visibility

source/plugin.cpp, source/plugin.hpp
Using the obs_module_file and obs_module_config_path macros works okay, but it comes with a slight overhead as well as additional requirements when passing it to C++ functions that expect certain rules to be fulfilled. By instead wrapping the actual functionality into our own functions and using those we can avoid most of the issues that come with the old approach.
The old behavior incorrectly relied on C++ to consider char* as a unicode string and would have a lot of boilerplate code repeated over many places.
Failure cases are properly handled, as well as unicode characters.
- #359 Configuration is not saved in the correct directory.
=> plugin: Implement proper functions to get config and data files

source/ui/ui-updater.cpp, source/ui/ui-updater.hpp, source/ui/ui.cpp
Fixes a launch freeze caused by the GDPR dialog. Reported by R1CH and several other users.
OBS Studio occasionally froze while starting up due to the GDPR dialog appearing too early.
The updater now waits for OBS Studio to be fully loaded, and then performs its actual work.
=> ui/updater: Don't require Qt interaction before OBS is ready

source/ui/ui.cpp, source/ui/ui.hpp
Fixes various other Qt issues that caused issues like #379 by moving the entire Qt logic to be based on an OBS notification instead of plugin load/unload.
Some platforms and systems may have had trouble using StreamFX.
No platform should have issues with StreamFX.
=> ui: Fix additional Qt issues

.github/workflows/main.yml
The majority of users should have already switched or upgraded to Ubuntu 20.04 at this point, so there is no point in building further Ubuntu 18.04 versions. This saves us some CI slots, and also reduces the number of target systems to actually support.
=> ci: Remove automatic build support for Ubuntu 18.04

CMakeLists.txt
Fixes various discovered CMake issues, such as CMake not propagating PARENT_SCOPE changes to the actual parent due to forgetting to use a `macro()`.
- The 3D Transform Filter wasn't built due to a typo.
- Some automatic disabling of a feature was not triggered.
- Some Windows-exclusive libraries were included automatically on non-Windows platforms.
- The 3D Transform Filter is now built again.
- Automatic disabling of features works again.
- No Windows-exclusive libraries are included anymore.
- #434 
- #458 
- #460 
- #461 
- #462 
- #463 
- #465 Linux Obstacles with ARM64
=> Fix various CMake issues

source/nvidia/cuda/nvidia-cuda.cpp
Some GCC versions complain about void* to any* casts. 
- #465
=> nvidia/cuda: Use reinterpret_case instead of static_cast

source/ffmpeg/tools.cpp
Both Rec. 601 and sRGB looked extremely wrong before, resulting in weird or warped colors. Since it is very difficult to find up to date and accurate information on standards, we should simply go for what has the most widespread support.
- sRGB colors were warped.
- Rec. 601 was completely wrong.
- Both color spaces should look "correct" now.
=> ffmpeg/tools: Fix incorrect transfer characteristics

CMakeLists.txt
The Windows installer was placed in the wrong directory.
The Windows installer is now in the correct place again.
=> cmake: (Windows) Fix incorrect reference to CMAKE_PACKAGE_PREFIX

source/filters/filter-color-grade.cpp, source/filters/filter-displacement.cpp, source/filters/filter-dynamic-mask.cpp, source/filters/filter-shader.cpp, source/gfx/shader/gfx-shader.cpp, source/gfx/shader/gfx-shader.hpp, source/sources/source-shader.cpp, source/transitions/transition-shader.cpp
See #501.
- 3D Transform: Direct Rendering
- Blur: Direct Rendering
- Color Grading: Buffered Rendering
- Displacement Mapping: Direct Rendering
- Dynamic Mask: Direct Rendering
- Nvidia Face Tracking: Direct Rendering (internally buffers)
- SDF Effects: Direct Rendering (internally buffers)
- Shaders: Buffered Rendering (internally buffers)
- Source Mirror: Buffered Rendering
- 3D Transform: Direct Rendering
- Blur: Direct Rendering
- Color Grading: Direct Rendering (internally buffers)
- Displacement Mapping: Buffered Rendering
- Dynamic Mask: Buffered Rendering
- Nvidia Face Tracking: Direct Rendering (internally buffers)
- SDF Effects: Direct Rendering (internally buffers)
- Shaders: Direct Rendering (internally buffers), except Transitions
- Source Mirror: Buffered Rendering
=> Enable Direct Rendering for Sources and Filters that support it

source/ui/ui-updater.cpp, source/ui/ui.cpp
On MacOS, Qt automatically replaced the OBS Studio About with the StreamFX About window, which is not what we want. By forcefully assigning every menu item to have no actual role, we hopefully prevent this from happening.
- StreamFX's About menu item replaced OBS Studio's About menu item and was not accessible.
- StreamFX's menu was the last entry.
- StreamFX's menu now appears in front of the Help menu.
- StreamFX's About menu item no longer replaces OBS Studio's About menu and is accessible.
=> Don't replace the OBS Studio About menu with StreamFXs

source/filters/filter-nv-face-tracking.cpp, source/nvidia/ar/nvidia-ar.cpp
Upgrades the NVIDIA Face Tracking filter to the latest SDK and makes it compatible with OBS Studio 27.x. Thanks to @jpark37 for the helpful help in the OBS discord.
- It broke.
- Outdated SDK
- It works again.
- Latest SDK.
=> filters/nvidia-face-tracking: Update for new SDK and OBS 27.x

CMakeLists.txt, source/nvidia/cuda/nvidia-cuda-context.cpp, source/nvidia/cuda/nvidia-cuda-obs.cpp, source/nvidia/cuda/nvidia-cuda.cpp, source/nvidia/cuda/nvidia-cuda.hpp, source/plugin.cpp, source/util/util-library.cpp, source/util/util-platform.cpp, source/util/util-platform.hpp
- CUDA and related information should be loaded as soon as possible, instead of on-demand.
- The primary context should not be destroyed by StreamFX.
- The stream has to be released _before_ the context is released.
- Some additional logging for the device information is nice to have.
=> Fix some parts of CUDA interaction code

.gitmodules, CMakeLists.txt, data/locale/en-US.ini, source/filters/filter-video-superresolution.cpp, source/filters/filter-video-superresolution.hpp, source/nvidia/cuda/nvidia-cuda-context.cpp, source/nvidia/cuda/nvidia-cuda-stream.cpp, source/nvidia/cuda/nvidia-cuda.cpp, source/nvidia/cv/nvidia-cv-image.cpp, source/nvidia/cv/nvidia-cv-image.hpp, source/nvidia/cv/nvidia-cv-texture.cpp, source/nvidia/cv/nvidia-cv-texture.hpp, source/nvidia/cv/nvidia-cv.cpp, source/nvidia/cv/nvidia-cv.hpp, source/nvidia/vfx/nvidia-vfx-superresolution.cpp, source/nvidia/vfx/nvidia-vfx-superresolution.hpp, source/nvidia/vfx/nvidia-vfx.cpp, source/nvidia/vfx/nvidia-vfx.hpp, source/plugin.cpp, source/util/util-profiler.cpp, source/util/util-profiler.hpp, source/util/utility.hpp
Adds/Implements the Video Super-Resolution filter which allows users with a supported upscaling provider to increase the resolution of their footage by up to 4x, while maintaining decent quality. This comes at some VRAM and GPU time cost, but it can make a 1280x720 camera look like a 3K camera.
At the current moment, only the following super resolution providers exist:
- NVIDIA Video Super-Resolution
=> Add/Implement Video Super-Resolution Filter

CMakeLists.txt, source/nvidia/cv/nvidia-cv-image.cpp, source/nvidia/cv/nvidia-cv-image.hpp, source/nvidia/cv/nvidia-cv-texture.cpp, source/nvidia/cv/nvidia-cv.hpp, source/nvidia/vfx/nvidia-vfx-superresolution.cpp
1. The CMake file didn't check if any provider was actually available, instead it checked for itself. With this patch it should now disable if no providers are enabled.
2. The function NvCVImage_Dealloc returns void, but was incorrectly treated as if it returned NvCVStatus.
3. `::streamfx::nvidia::cv::image` needs to store the alignment used for resize() calls, as otherwise we end up with very weird misalignments and driver crashes.
4. The Super-Resolution wrapper should use resize instead of reallocate, now that the function has been fixed.
There are a few cases where Video Super-Resolution crashes or results in a driver reset, which is not what users want to see.
=> Fixes and Enhancements for Video Super-Resolution filter

source/plugin.cpp
Fixes a failure to load the plugin if the GPU is not an NVIDIA GPU or the Driver is outdated.
People want to use the Testing versions in Production, no matter how often I tell people not to.
=> plugin: Don't leak CUDA load exceptions

source/util/util-logging.cpp
vsnprintf is allowed to modify vargs, and at least GCC under Linux does
modify it, causing a segfault on any log call.
This creates a duplicate vargs to avoid this issue.
It fixes a bug
- [ X ] I will become the maintainer for this part of code.
- [  ] I have tested this code on all supported Platforms.
I only have one platform available to me.
Relates to #630 New Unified logging causes crash on start under Linux/Gentoo
Closes: #630
=> Avoid vargs reuse

.github/workflows/main.yml
Prevents CI from running twice for pull requests coming from the same repository.
CI was getting overloaded with double the workload every time there was a small change to a PR from this repo.
=> ci: Pull Requests shouldn't invoke CI twice

source/util/util-library.cpp
LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR requires an absolute path, and does not work with relative paths, LOAD_LIBRARY_SEARCH_DEFAULT_DIRS is the opposite.
Makes things load on Windows again.
=> util/library: Don't mix incompatible parameters

data/effects/lut.effect, data/effects/shared.effect, data/effects/standard.effect, data/effects/transform.effect, data/effects/virtual-greenscreen.effect, source/filters/filter-blur.cpp, source/filters/filter-color-grade.cpp, source/filters/filter-displacement.cpp, source/filters/filter-dynamic-mask.cpp, source/filters/filter-sdf-effects.cpp, source/filters/filter-transform.cpp, source/gfx/blur/gfx-blur-box-linear.cpp, source/gfx/blur/gfx-blur-box.cpp, source/gfx/blur/gfx-blur-dual-filtering.cpp, source/gfx/blur/gfx-blur-gaussian-linear.cpp, source/gfx/blur/gfx-blur-gaussian.cpp, source/obs/gs/gs-effect.cpp, source/obs/gs/gs-effect.hpp, source/obs/gs/gs-mipmapper.cpp
- Adds a simple pre-processor to handle basic preprocessor commands like `#include` in a useful way. This fixes some compatibility problems across graphics APIs.
- Adjusts many locations which incorrectly did not handle the exceptions from shaders correctly.
- Adjusts all effect files which use `texture2D` instead of `texture2d`
- Fixes #696
=> Fix Effect integration

source/encoders/encoder-ffmpeg.cpp, source/ffmpeg/tools.cpp
This bug predates the merge into StreamFX and was present in the original release as a separate plugin. libOBS has never sampled Chroma at Center as far as I can look back into its history.
Fixes #676
Fixes decoders decoding chroma as if it was in another location when the software encode path is in use. Did not affect hardware accelerated encodes.
=> encoder/ffmpeg: libOBS samples Chroma at Top, not Center

.github/workflows/main.yml, CMakeLists.txt
An unknown update broke Code Signing on Windows, resulting in Windows only building unsigned binaries. This fixes it and also allows multiple cmake-codesign projects to use different certificates entirely.
=> cmake: Fix code signing on Windows

source/filters/filter-autoframing.cpp
It was incorrectly assumed that only normal video sources would be used with the filter, not async video sources.
- #739
=> filters/autoframing: Always set projection matrix

.github/workflows/main.yml
GCC is still widely used, and sometimes the only supported compiler at all. Should have verified the previous PR added GCC before trusting my own brain to have understood everything correctly.
=> ci: Add GCC back to the build

.github/workflows/main.yml
Removes the mostly useless self-signed certificate from CI. 
=> ci: Remove Code Signing with self-signed certificate

source/gfx/gfx-source-texture.cpp
Compiling fails if Debug or Profiling is enabled, which is sub-optimal.
=> Fix compilation errors with Debug and/or Profiling

.github/workflows/main.yml
The current build pipeline is extremely convoluted for no real gain. Build time can be reduced by opting to merge some of the stages into one element instead, such as platforms and build type.
=> Deduplicate CI build pipeline

source/obs/gs/gs-effect.cpp
The use of const references breaks '#include' for relative paths.
=> obs/gs/effect: Revert #836

source/filters/filter-dynamic-mask.cpp, source/gfx/shader/gfx-shader-param-texture.cpp, source/gfx/shader/gfx-shader-param-texture.hpp, source/obs/obs-weak-source.hpp
Texture inputs to shaders have become incredibly unstable with later versions, which results in crashes and freezes. As this situation is very much unwanted, this PR should improve the situation massively.
=> #881: Texture inputs to Shaders are unstable

data/locale/en-US.ini, source/encoders/encoder-aom-av1.cpp, source/encoders/encoder-aom-av1.hpp
As the integrated 'AOM AV1' and 'SVT-AV1' encoders serve the same purpose, there is no point in providing this anymore.
=> Deprecate AOM AV1 encoder

CMakeLists.txt
Nlohmann-json is [used in the about dialog](https://github.com/Xaymar/obs-StreamFX/blob/master/source/ui/ui-about.cpp#L31), yet wasn't required when building the front-end, leading to failing compilation. This ensures that it is correctly required. See https://github.com/flathub/flathub/pull/3159#issuecomment-1235303799.
=> cmake: Require nlohmann-json when building the front-end

source/encoders/handlers/prores_aw_handler.cpp, source/encoders/handlers/prores_aw_handler.hpp
Removes the useless Key-Frame options from the ProRes encoder. It's an I-only encoder which doesn't actually support this in the first place.
=> encoder/handler/prores_aw: Don't enable Key-Frame options

source/encoders/handlers/dnxhd_handler.cpp
Fixes a bug with the DNxHR encoder on some architectures that use a different endianness than StreamFX's DNxHR integration.
=> encoder/handler/dnxhd: Use endian-independent formats

templates/windows/installer.iss.in
This is a combination of multiple related changes to make one thing better:
- The directory page is no longer conditionally hidden. For some reason people keep moving the obs-studio directory instead of just installing it into the correct location in the first place. What can you do, other than to tell people to stop doing it... 🤷‍♂️
- We now check for the correct mutexes, instead of some weird names.
- The portable installation now has a proper uninstaller extracted to it.
- System wide installations now follow the standard introduced in OBS Studio v0.15.0, which allows loading plugins from `%ProgramData%\obs-studio\plugins\`. This change appears to have gone unnoticed entirely, as even @OBSProject's own [obs-plugintemplate](https://github.com/obsproject/obs-plugintemplate) does not use …
=> Improve Windows installer with proper System install location, Current User install method, and better UI

CMakeLists.txt, source/filters/filter-autoframing.cpp, source/filters/filter-autoframing.hpp, source/filters/filter-denoising.cpp, source/filters/filter-denoising.hpp, source/filters/filter-upscaling.cpp, source/filters/filter-upscaling.hpp, source/filters/filter-virtual-greenscreen.cpp, source/filters/filter-virtual-greenscreen.hpp, source/plugin.cpp, source/plugin.hpp, source/updater.cpp, source/updater.hpp, source/util/util-threadpool.cpp, source/util/util-threadpool.hpp
While the previous approach of a static thread pool worked, it was sub-optimal in its resource usage. Many of the threads would never see a single task, and simply permanently sleep. This seems like a good idea, except that sleeping threads still end up in the scheduler, and thus waste a tiny amount of resources.
It is better to instead dynamically spawn threads when needed and only keeping the bare minimum around all the time. These dynamically spawned threads are also explicitly set to background priority which further reduces scheduling overhead. Finally optimizing the memory layout to prevent unwanted false sharing should also keep sporadic wake ups at a minimum.
This new model should be able to handle many more tasks than ever before, but is still not as optimal as it could be.
- I …
=> Implement dynamically scaled Thread Pool

source/configuration.cpp, source/configuration.hpp, source/plugin.cpp, source/ui/ui.cpp, source/updater.cpp
To prevent excessive data loss, the configuration should be saved after some time has passed, instead of right before quitting OBS Studio. This addresses #805.
=> Save configuration after ~100ms have passed

templates/windows/installer.iss.in
Portable mode shouldn't create icons, and now doesn't anymore.
=> templates/windows/installer: Don't create Icons in Portable mode
