Xaymar/obs-StreamFX

.github/workflows/main.yml, appveyor.yml, ci/builder.js, ci/packager.js
Integrates Github Actions as a CI provider for future use, while also splitting packaging and building apart for better workflow.
The build script additionally now properly follows the build chain for x32 and x64 independently and will not try to build architectures for which there is no generator set.
Relying on compilation results from AppVeyor is way too slow, with up to 10 minutes delay for a single commit to build. It only gets worse the more commits there are, which isn't great. Therefore AppVeyor is now only used for releasing tags until that can also be moved over to Github Actions.
Extensively over several commits. Code is currently not compatible with Visual Studio 2019, which needs to be fixed.
- New feature (non-breaking change which adds functionality)
=> ci: Attempt integration of Github Actions

.gitmodules, CMakeLists.txt, cmake/modules/FindNVAR.cmake, data/effects/pack-unpack.effect, data/locale/en-US.ini, source/filters/filter-nv-face-tracking.cpp, source/filters/filter-nv-face-tracking.hpp, source/nvidia/ar/nvidia-ar-feature.cpp, source/nvidia/ar/nvidia-ar-feature.hpp, source/nvidia/ar/nvidia-ar.cpp, source/nvidia/ar/nvidia-ar.hpp, source/nvidia/cuda/nvidia-cuda-context-stack.cpp, source/nvidia/cuda/nvidia-cuda-context-stack.hpp, source/nvidia/cuda/nvidia-cuda-context.cpp, source/nvidia/cuda/nvidia-cuda-context.hpp, source/nvidia/cuda/nvidia-cuda-gs-texture.cpp, source/nvidia/cuda/nvidia-cuda-gs-texture.hpp, source/nvidia/cuda/nvidia-cuda-memory.cpp, source/nvidia/cuda/nvidia-cuda-memory.hpp, source/nvidia/cuda/nvidia-cuda-stream.cpp, source/nvidia/cuda/nvidia-cuda-stream.hpp, source/nvidia/cuda/nvidia-cuda.cpp, source/nvidia/cuda/nvidia-cuda.hpp, source/plugin.cpp
Ever wished you had a professional camera operator to highlight and follow the action, ensuring the audience never misses a beat? Thanks to NVIDIA, you can now do this at home for free! The new NVIDIA AR SDK unlocks augmented reality features, including motion tracking for faces.
This allows me to provide you with an automated zoom and cropping solution for your video camera to transform your streams into a slick, polished broadcast, where you’ll always be the star of the show. Don’t forget - everything is customizable so the possibilities are endless. You can even recreate that Futurama squinting meme if you wanted to (with some scripting)!
The filter requires compatible Nvidia RTX hardware and the Nvidia AR SDK Runtime to be installed ahead of time. This filter is considered "stable" …
=> New Filter: Nvidia Face Tracking

.clang-format, source/encoders/ffmpeg-encoder.cpp, source/encoders/ffmpeg-encoder.hpp, source/encoders/handlers/nvenc_h264_handler.cpp, source/filters/filter-dynamic-mask.cpp, source/transitions/transition-shader.cpp
Fixes a missing code include, include ordering, and some formatting.
- Bug fix (non-breaking change which fixes an issue)
- Code cleanup (non-breaking change which makes code smaller or more readable)
=> Fix coding Errors

data/locale/en-US.ini
Fix missing '[Alpha]' in Dynamic Mask
=> locale: Fix missing '[Alpha]'

.github/workflows/main.yml, source/filters/filter-sdf-effects.cpp, source/filters/filter-sdf-effects.hpp, source/filters/filter-transform.cpp, source/filters/filter-transform.hpp, source/sources/source-mirror.hpp, source/util-profiler.cpp
Fixes most/all issues described in #146, which seem to be Clang exclusive.
- #146 Various compiling issues on Clang
=> project: Actually fix issues described in #146

.github/workflows/main.yml
=> ci: Also trigger on tag creation

.github/workflows/main.yml, source/gfx/shader/gfx-shader.cpp
=> Beta 2 Hotfix 2 

source/filters/filter-blur.cpp, source/gfx/blur/gfx-blur-box-linear.cpp, source/gfx/blur/gfx-blur-box.cpp, source/gfx/blur/gfx-blur-dual-filtering.cpp, source/gfx/blur/gfx-blur-gaussian-linear.cpp, source/gfx/blur/gfx-blur-gaussian.cpp
Adds debug markers to some code in order to track performance in GPU debuggers and profilers.
=> Add Debug Markers for Performance tracking

source/util-threadpool.cpp, source/util-threadpool.hpp
Adds the ability to cancel tasks queued in the threadpool, in order to improve threading stability. Prevents crashes in cases where a source is deleted but work is still queued. Does not prevent crashes where a source is deleted while work is being executed, this must be protected by using hard source references.
=> Allow threadpool tasks to be cancelled.

data/locale/en-US.ini, source/ui/ui-about.cpp, ui/about.ui
Adds the current StreamFX version to the "About StreamFX" dialog.
=> ui/about: Add version information

CMakeLists.txt
Adds AppleClang support to cmake-clang.
- Fixes #229 Build fails due to missing entry for AppleClang
=> cmake: Update Clang integration to support AppleClang

source/configuration.cpp, source/ui/ui-about.cpp
Formatting wasn't properly applied for some previous PRs.
=> Fix applied formatting

CMakeLists.txt
Adds support for signing code using the Windows SDK signtool application.
=> cmake: Add support for code signing

ui/about-entry.ui
Fixes some incorrect QSS that was left over during testing.
=> ui/about-entry: Fix incorrect QSS

CMakeLists.txt
Update version for 0.9.0a1 release.
=> project: Version 0.9.0a1

CODEOWNERS
Adds a CODEOWNERS file so that Github can authorize certain changes.
=> project: Add CODEOWNERS file

source/plugin.cpp
=> plugin: Fix missing include

CMakeLists.txt
=> cmake: Fix Clang toolset support

source/ui/ui-about.cpp
Updates the current 'Thank You' entries to the entire list of current supporters, including those that have not submitting URLs to include in the dialog.
=> Add new 'Thank You' entries

source/util-threadpool.cpp, source/util-threadpool.hpp
Tasks should not leak exceptions, so it is better if we actually log them instead of silently ignoring them.
=> util/threadpool: Show warnings for uncaught exceptions

.github/workflows/main.yml, .github/workflows/validate.yml, source/encoders/encoder-ffmpeg.cpp, source/encoders/handlers/debug_handler.cpp, source/filters/filter-nv-face-tracking.cpp, source/gfx/shader/gfx-shader-param-basic.cpp, source/transitions/transition-shader.cpp
Sometimes clang-format does not run as expected, and formatting is not applied as expected, therefore we need to add formatting validation to all PRs. If the validation fails, the PR can't be merged.
=> Add validation for code formatting

source/ui/ui-about.cpp
=> ui/about: Fix incorrect icon for YouTube URL

.github/workflows/main.yml
=> ci: Also run on tags

.github/pull_request_template.md
Adds some additional information required for Pull Requests to be considered valid, in order to quickly identify any surface level issues.
=> project: Improve Pull Request Template

source/util/util-curl.hpp
Fixes a compile error on Mac.
- #348
=> util/curl: Add missing include for vector

source/obs/obs-source-factory.hpp
Fixes a black screen issue if a filter happens to run into an unexpected issue which it considers unrecoverable.
If a filter did not catch an exception, it would simply break rendering everything.
Filters now render the original source if things went wrong.
=> obs/source-factory: Skip broken filter rendering by default

CMakeLists.txt, source/common.hpp, source/util/util-bitmask.hpp, source/util/util-library.cpp, source/util/util-library.hpp, source/util/utility.hpp
Splits bitmasking functionality into its own file, and improves util::library code.
=> util: Improve util::library and split bitmask functionality

source/configuration.cpp, source/filters/filter-blur.cpp, source/filters/filter-color-grade.cpp, source/filters/filter-displacement.cpp, source/filters/filter-dynamic-mask.cpp, source/filters/filter-sdf-effects.cpp, source/gfx/blur/gfx-blur-box-linear.cpp, source/gfx/blur/gfx-blur-box.cpp, source/gfx/blur/gfx-blur-dual-filtering.cpp, source/gfx/blur/gfx-blur-gaussian-linear.cpp, source/gfx/blur/gfx-blur-gaussian.cpp, source/gfx/shader/gfx-shader.cpp, source/obs/gs/gs-effect.cpp, source/obs/gs/gs-mipmapper.cpp, source/util/util-library.cpp
Fixes bad unicode handling caused by not fully reading the C++17 specification and instead just hammering away at code that might work. 
Unicode characters caused crashes and invalid/undefined behavior.
Unicode characters no longer cause crashes and are correctly handled.
- Fixes #359: Unicode characters cause problems
=> Fix incorrect Unicode handling

CMakeLists.txt
* encoders/ffmpeg: Implement AMF H.264 and H.265 handlers
* locale: New Crowdin updates (Turkish) (#373)
* examples: Added adjustable luminance to hexagon size (#364)
* cmake: Add option to override download versions and hashes
=> project: Version 0.10.0a

CMakeLists.txt
Changes the versioning system to an improved design based on git describe.
New versions **required** changes to CMakeLists.txt which was an additional commit.
New versions no longer require changes to CMakeLists.txt and are automatically gathered from tag information.
=> cmake: Improve versioning system

cmake/DownloadProject.CMakeLists.cmake.in
=> cmake: Fix DownloadProject version warning

data/examples/shaders/filter/pixelation.effect
Added a pixelation effects
Partial pixelation effect can be applied.
none.
[
](url)
none.
thanks.
=> Add Pixelation effects

source/ui/ui.cpp
=> ui: Don't reference Updater if it's been disabled

CMakeLists.txt
Versioning may fail when the version tag matches the current commit.
Versioning should always succeed.
=> cmake: Always use long git describe

CMakeLists.txt
- #437 Use 'git describe --tags' for versioning.
- #439 Add support for overriding the automatically detected version.
- #454 Fixed new versioning code breaking when the tag is on the current commit.
- #427, #428 Fix Qt interaction before OBS Studio is actually ready.
- #452 Fixed building without updater but with UI.
- #447 Redesigned Color Grading to support two rendering modes:
- Direct Rendering applies the entire color grading function to every single pixel, and is thus more accurate, but much slower.
- #-Bit LUT Rendering first applies the color grading function to a LUT that varies in accuracy, and then uses that LUT to render the actual output instead, which is much faster but less accurate.
- #447 Optimized Direct Rendering in Color Grading to be up to 25% faster, while using 50% …
=> project: Version 0.10.0a1

source/obs/gs/gs-vertex.hpp
=> obs/gs/vertex: Don't include unused headers

CMakeLists.txt
* 3D Transform should now appear again.
* Automatic disabling of unsupported features should now work in CMake.
* Fixed a compilation error on some versions of GCC.
=> project: Version 0.10.0a2

CMakeLists.txt
=> project: 0.10.0b1

.github/workflows/main.yml, .github/workflows/validate.yml, CMakeLists.txt, cmake/util.cmake
- CI would fail when installing Qt5
- Linker path adjustment for obs-frontend-api.dylib was not run.
- CI downloads Qt5 again.
- Linker path adjustment for obs-frontend-api.dylib is being run.
=> Fix issues with Continuous Integration

.github/workflows/main.yml, CMakeLists.txt
- Qt5, libOBS and OBS Dependencies was not cached.
- Qt5, libOBS and OBS Dependencies is now cached.
=> ci: Add caching for many steps

CMakeLists.txt
* Fixed a bug preventing versions from being parsed correctly in CMake.
* Fixed a bug introduced between 0.9.3 and 0.10.0b1 which broke transparency support for Color Grading.
* Added support for direct rendering to some sources/filters/transitions.
* Added .pkg based Installer for MacOS, thanks to @cpyarger.
* Updated translations from Crowdin.
=> project: Version 0.10.0b2

CMakeLists.txt
=> Version 0.10.0b3

CMakeLists.txt
=> project: Version 0.10

.github/workflows/main.yml
2nd part of #540, adjusts the CI to the same version.
- CI used 26.1.x
- CI uses 27.0.0-rc2
=> Update CI to libOBS 27.0.0-rc2

.github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/issue.yml
Fixes the remaining issues with the issue templates
=> project: Fix incorrect template settings

.github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/issue.yml
=> Update issue template

.github/ISSUE_TEMPLATE/issue.yml, CMakeLists.txt
=> project: Version 0.11.0a1

.github/pull_request_template.md
Pull Requests on GitHub don't support the modern templating system yet.
Removes annoying header from the pull request.
=> project: Fix pull request template

.github/workflows/codeql-analysis.yml
Add some form of code quality guarantees to the project.
Improve the code base.
=> ci: Add CodeQL

source/filters/filter-nv-face-tracking.cpp, source/filters/filter-nv-face-tracking.hpp, source/nvidia/ar/nvidia-ar-feature.cpp, source/nvidia/ar/nvidia-ar-feature.hpp, source/nvidia/ar/nvidia-ar.cpp, source/nvidia/ar/nvidia-ar.hpp, source/nvidia/cuda/nvidia-cuda-context.cpp, source/nvidia/cuda/nvidia-cuda-context.hpp, source/nvidia/cuda/nvidia-cuda-gs-texture.cpp, source/nvidia/cuda/nvidia-cuda-gs-texture.hpp, source/nvidia/cuda/nvidia-cuda-memory.cpp, source/nvidia/cuda/nvidia-cuda-memory.hpp, source/nvidia/cuda/nvidia-cuda-obs.cpp, source/nvidia/cuda/nvidia-cuda-obs.hpp, source/nvidia/cuda/nvidia-cuda-stream.cpp, source/nvidia/cuda/nvidia-cuda-stream.hpp, source/nvidia/cuda/nvidia-cuda.cpp, source/nvidia/cuda/nvidia-cuda.hpp
Adjusts additional parts to the Coding Guidelines, as they should have been from the start. 
The project itself must follow the coding guidelines if they are to be enforced on others.
=> Adjust additional parts to the Coding Guidelines

.github/workflows/codeql-analysis.yml, .github/workflows/validate.yml
=> ci: Don't run CodeQL on translation changes

.github/ISSUE_TEMPLATE/issue.yml, CMakeLists.txt
Release 0.11.0a2
Releases 0.11.0a2
=> project: Version 0.11.0a2

.github/ISSUE_TEMPLATE/issue.yml, CMakeLists.txt
=> project: Version 0.11.0a3

CMakeLists.txt, data/effects/blur/box-linear.effect, data/effects/blur/common.effect, data/effects/color_conversion_rgb_hsl.effect, data/effects/color_conversion_rgb_hsv.effect, data/effects/lut.effect, data/effects/mask.effect, data/effects/mipgen.effect, data/effects/sdf/sdf-producer.effect, data/effects/shared.effect, data/examples/shaders/filter/posterize.effect, data/examples/shaders/filter/vignette.effect, data/examples/shaders/source/shadertoy-3tlXWS.effect, data/examples/shaders/source/shadertoy-MtcGD7.effect, data/examples/shaders/source/shadertoy-XljBW3.effect, data/examples/shaders/source/shadertoy-Xsl3RX.effect, data/examples/shaders/transition/pixelator.effect
=> project: Apply Coding Guidelines

source/encoders/handlers/nvenc_shared.cpp, source/filters/filter-blur.cpp, source/filters/filter-color-grade.cpp, source/filters/filter-displacement.cpp, source/filters/filter-dynamic-mask.cpp, source/filters/filter-nv-face-tracking.cpp, source/filters/filter-sdf-effects.cpp, source/filters/filter-shader.cpp, source/filters/filter-transform.cpp, source/filters/filter-video-superresolution.cpp, source/gfx/lut/gfx-lut.cpp, source/nvidia/cuda/nvidia-cuda-context.cpp, source/nvidia/cv/nvidia-cv-image.hpp, source/nvidia/cv/nvidia-cv.cpp, source/nvidia/vfx/nvidia-vfx-superresolution.cpp, source/nvidia/vfx/nvidia-vfx.cpp, source/sources/source-mirror.cpp, source/sources/source-shader.cpp, source/transitions/transition-shader.cpp, source/ui/ui-updater.cpp, source/updater.cpp, source/util/util-threadpool.cpp
Prevents some startup crashes from happening by simply skipping the code in question entirely, logging the exception. Should make some more recent versions work partially, even if users pull a stupid.
Even if you provide all necessary information in multiple places, users will randomly pull a stupid and insist they are in the right.
=> Don't leak Exceptions all over the place

CMakeLists.txt, data/locale/en-US.ini, source/filters/filter-denoising.cpp, source/filters/filter-denoising.hpp, source/filters/filter-upscaling.cpp, source/filters/filter-upscaling.hpp, source/filters/filter-video-superresolution.cpp, source/filters/filter-video-superresolution.hpp, source/nvidia/cuda/nvidia-cuda.cpp, source/nvidia/cuda/nvidia-cuda.hpp, source/nvidia/vfx/nvidia-vfx-denoising.cpp, source/nvidia/vfx/nvidia-vfx-denoising.hpp, source/nvidia/vfx/nvidia-vfx-effect.cpp, source/nvidia/vfx/nvidia-vfx-effect.hpp, source/nvidia/vfx/nvidia-vfx-superresolution.cpp, source/plugin.cpp
=> Add or Improve NVIDIA Maxine based Filters

CMakeLists.txt
=> cmake: Fix incorrect target for interface include directories

data/locale/en-US.ini
=> locale: Fix incorrect key for provider

.github/ISSUE_TEMPLATE/issue.yml, .github/PULL_REQUEST_TEMPLATE/feature.md, .github/PULL_REQUEST_TEMPLATE/fix.md, CMakeLists.txt
=> project: Version 0.11.0a8

media/README.md
Properly defines the license and usage guidelines for all StreamFX media. Before now, all StreamFX media was not sublicensed properly, meaning their usage in any content was in breach of Copyright law by default. With this, a proper license is published.
=> Define License for Media

.github/workflows/main.yml
Possibly fixes random Pull Request failures on Windows and Mac, as the secrets are undefined.
=> ci: Don't perform tasks relying on secrets in pull requests

.github/ISSUE_TEMPLATE/issue.yml, CMakeLists.txt
=> project: Version 0.11.0b1

source/obs/gs/gs-mipmapper.cpp
Fixes broken Mip-Mapping introduced by #705, as well as broken sRGB mip-mapping.
- #721
=> Fix Mip-mapping for sRGB and Direct3D

data/examples/shaders/filter/displace.effect, data/examples/shaders/filter/fxaa.effect, source/obs/gs/gs-effect.cpp
Fixes a few Shaders which were not rendering correctly:
- FXAA was set to Point, but requires Linear.
- FXAA was only compiling on Direct3D, now also compiles on OpenGL
- Effect files were missing their prefixed defines.
- Displacement Mapping was implicitly casting float4 to float2.
=> Fix various Shaders

source/gfx/shader/gfx-shader-param-texture.cpp, source/gfx/shader/gfx-shader.cpp
We enabled blending, which meant that the Alpha channel was never stored into the output. Also sRGB was enabled for some reason.
=> Fix Shaders not rendering correctly

.github/ISSUE_TEMPLATE/issue.yml, CMakeLists.txt
=> project: Version 0.11.0b2

.github/workflows/authors.yml
=> ci: Fix some invalid commands

.github/workflows/authors.yml, tools/generate-contributors.js
=> ci: Provide proper identification

.github/workflows/authors.yml
=> ci: Only regenerate authors on dispatch

AUTHORS.md, data/thanks.json
=> Remove "Github Actions" from the contributors

.github/ISSUE_TEMPLATE/issue.yml, CMakeLists.txt
=> project: Version 0.11.0b3

.github/workflows/authors.yml, data/locale/en-US.ini, source/ui/ui-about-entry.cpp, source/ui/ui-about.cpp, source/ui/ui-about.hpp, ui/about-entry.ui, ui/about.ui
Replaces the old manually written credits entries with automatically generated entries. This is necessary in order to keep up with the number of contributors, translators and supporters.
=> Use auto-generated credits for "About StreamFX"

.github/workflows/main.yml
=> ci: Properly install Qt@5 on MacOS

source/ui/ui-about.cpp
These just break the flow, with no visual improvement.
=> ui/about: Remove additional spacers

.github/ISSUE_TEMPLATE/issue.yml, CMakeLists.txt
=> project: Version 0.11.0c1

.github/workflows/main.yml
An attempt at permanently fixing the installation of Packages until a better way is found.
=> ci: Ignore specific Packages versions

.github/ISSUE_TEMPLATE/issue.yml, CMakeLists.txt
=> project: Version 0.12.0a1

.github/workflows/main.yml, .github/workflows/validate.yml
Adds ClangCL builds, as well as updates the Windows SDK to a fixed version.
=> Add ClangCL, and update Windows SDK requirements

.github/workflows/main.yml, .github/workflows/validate.yml
Allow some of matrix entries to fail, as support for everything isn't guaranteed.
=> ci: Allow failures for experimental CI tests

.github/workflows/main.yml, .github/workflows/validate.yml, CMakeLists.txt, source/gfx/gfx-source-texture.hpp
Forces CI to use a specific version of LLVM/Clang for reasons of sanity.
=> ci: Use specific LLVM/Clang versions

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/issue.yml, .github/pull_request_template.md, .github/workflows/main.yml
Removes pointless build stages, and improves the templates for Issues and PRs
=> Improve GitHub integration

.github/ISSUE_TEMPLATE/config.yml, tools/argparse.sh
Fixes incorrect tabs being placed into config.yml for GitHub's issue template configuration.
=> project: Fix incorrect tabs in YAML

CMakeLists.txt
=> cmake: Add support for Qt6

.github/workflows/main.yml, CMakeLists.txt
Updates the libOBS submodule to 28.0.0-rc1
=> Update libOBS to 28.0.0-rc1

data/locale/en-US.ini, source/encoders/handlers/amf_h264_handler.hpp, source/filters/filter-displacement.cpp, source/filters/filter-displacement.hpp
Adds the missing deprecation notices.
=> Add missing deprecation notices

CONTRIBUTING.md
=> project: Updating contributing guidelines

source/ffmpeg/tools.cpp
=> Add support for HDR formats
